# Generated by Django 3.2.12 on 2022-06-05 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavordetail',
            name='bean',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.beans'),
        ),
        migrations.AlterField(
            model_name='flavordetail',
            name='detail',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
