# Generated by Django 3.2.12 on 2022-06-05 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220605_0645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flavordetail',
            old_name='bean',
            new_name='beans',
        ),
    ]
