# Generated by Django 3.2.12 on 2022-06-05 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_bean_flavordetail_beans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavordetail',
            name='beans',
        ),
        migrations.RemoveField(
            model_name='flavordetail',
            name='flavor',
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=100)),
                ('beans', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.beans')),
            ],
        ),
        migrations.AlterField(
            model_name='flavordetail',
            name='detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.flavor'),
        ),
    ]
