# Generated by Django 3.2.12 on 2022-06-05 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220605_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavor',
            name='beans',
        ),
        migrations.AlterField(
            model_name='flavor',
            name='flavor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.beans'),
        ),
    ]
