# Generated by Django 3.2.12 on 2022-06-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220605_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavordetail',
            name='beans',
        ),
        migrations.AddField(
            model_name='flavordetail',
            name='beans',
            field=models.ManyToManyField(to='main.Beans'),
        ),
    ]
