# Generated by Django 3.2.12 on 2022-06-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220605_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beans',
            name='roast',
            field=models.CharField(choices=[('Light', 'Light'), ('Medium', 'Medium'), ('Dark', 'Dark')], max_length=50),
        ),
    ]
