# Generated by Django 3.2.12 on 2022-06-05 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_beans_roast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beans',
            old_name='flavor1',
            new_name='flavor',
        ),
        migrations.RenameField(
            model_name='beans',
            old_name='flavor2',
            new_name='flavor_detail',
        ),
        migrations.RemoveField(
            model_name='beans',
            name='flavor3',
        ),
    ]
